#!/usr/bin/python

import os
import sys
import nltk
import pyPdf
import magic
import sqlite3

home = os.getcwd()+'/Content'

conn = sqlite3.connect('Data.db')
conn.text_factory = str
db = conn.cursor()

file_stack = []

for path, subdirs, files in os.walk(home):
	for name in files:
		a_file = os.path.join(path, name)
		if a_file[:a_file.rfind('/')].find('.') == -1:
			file_stack.append( os.path.join(path, name) )
print 'Probing Complete'

i=0

data = db.execute('select * from DATA')
queries = []
for a_line in data:
	if a_line[1] not in file_stack:
		queries.append("delete from DATA where Name = '%s';" % a_line[0])

for query in queries:
	db.execute(query)

print i 
conn.commit()
conn.close()
