#!/usr/bin/python

import os
import sys
import nltk
import pyPdf
import magic
import sqlite3


from PIL import Image
from ID3 import *

execfile('Extensions')
execfile('Scraper')

home = os.getcwd()+'/Content'
#home = os.getcwd()+'/Bhuntu'
#home = '/home'



os.system('rm Data.db')
conn = sqlite3.connect('Data.db')
conn.text_factory = str
db = conn.cursor()
db.execute('create table DATA (name text,target text,type text,metadata text,content text)')

file_stack = []


no_of_file =  0
magic_error = 0
audio_error = 0
image_error = 0
pdf_error = 0
pmeta_error = 0
db_error = 0

for path, subdirs, files in os.walk(home):
#	for subdir in subdirs:
#		file_stack.append(os.path.join(path, subdir))

	for name in files:
		no_of_file+=1
		a_file = os.path.join(path, name)
		if a_file[:a_file.rfind('/')].find('.') == -1:
			file_stack.append( os.path.join(path, name) )
print 'Probing Complete'

file_no = 0
for a_file in file_stack:
	file_no+=1
	print file_no
	a = scraper(a_file)
	a.scrape()

print 'no of file: '+str(no_of_file)
print 'magic error: '+str(magic_error)
print 'audio error: '+str(audio_error)
print 'image error: '+str(image_error)
print 'pdf error: '+str(pdf_error)
print 'pmeta error: '+str(pmeta_error)
print 'db error: '+str(db_error)
print 'total error: '+str(magic_error+audio_error+image_error+pdf_error+pmeta_error+db_error)
try:
	print (magic_error+audio_error+image_error+pdf_error+pmeta_error+db_error)*100.00000/no_of_file
except Exception:
	print 'No File'

conn.commit()
conn.close()
